// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_definition.proto

package example.proto.user;

public final class UserDefProto {
  private UserDefProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserDefinitionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:example.UserDefinition)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string userName = 1;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>string userName = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>int32 id = 2;</code>
     */
    int getId();

    /**
     * <code>string email = 3;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>string phoneNum = 4;</code>
     */
    java.lang.String getPhoneNum();
    /**
     * <code>string phoneNum = 4;</code>
     */
    com.google.protobuf.ByteString
        getPhoneNumBytes();
  }
  /**
   * Protobuf type {@code example.UserDefinition}
   */
  public  static final class UserDefinition extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:example.UserDefinition)
      UserDefinitionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserDefinition.newBuilder() to construct.
    private UserDefinition(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserDefinition() {
      userName_ = "";
      id_ = 0;
      email_ = "";
      phoneNum_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserDefinition(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            case 16: {

              id_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              phoneNum_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return example.proto.user.UserDefProto.internal_static_example_UserDefinition_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return example.proto.user.UserDefProto.internal_static_example_UserDefinition_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              example.proto.user.UserDefProto.UserDefinition.class, example.proto.user.UserDefProto.UserDefinition.Builder.class);
    }

    public static final int USERNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object userName_;
    /**
     * <code>string userName = 1;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <code>string userName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 3;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONENUM_FIELD_NUMBER = 4;
    private volatile java.lang.Object phoneNum_;
    /**
     * <code>string phoneNum = 4;</code>
     */
    public java.lang.String getPhoneNum() {
      java.lang.Object ref = phoneNum_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phoneNum_ = s;
        return s;
      }
    }
    /**
     * <code>string phoneNum = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneNumBytes() {
      java.lang.Object ref = phoneNum_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phoneNum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userName_);
      }
      if (id_ != 0) {
        output.writeInt32(2, id_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
      }
      if (!getPhoneNumBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, phoneNum_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userName_);
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
      }
      if (!getPhoneNumBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, phoneNum_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof example.proto.user.UserDefProto.UserDefinition)) {
        return super.equals(obj);
      }
      example.proto.user.UserDefProto.UserDefinition other = (example.proto.user.UserDefProto.UserDefinition) obj;

      boolean result = true;
      result = result && getUserName()
          .equals(other.getUserName());
      result = result && (getId()
          == other.getId());
      result = result && getEmail()
          .equals(other.getEmail());
      result = result && getPhoneNum()
          .equals(other.getPhoneNum());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + PHONENUM_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneNum().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static example.proto.user.UserDefProto.UserDefinition parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static example.proto.user.UserDefProto.UserDefinition parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static example.proto.user.UserDefProto.UserDefinition parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static example.proto.user.UserDefProto.UserDefinition parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static example.proto.user.UserDefProto.UserDefinition parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static example.proto.user.UserDefProto.UserDefinition parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static example.proto.user.UserDefProto.UserDefinition parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static example.proto.user.UserDefProto.UserDefinition parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static example.proto.user.UserDefProto.UserDefinition parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static example.proto.user.UserDefProto.UserDefinition parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static example.proto.user.UserDefProto.UserDefinition parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static example.proto.user.UserDefProto.UserDefinition parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(example.proto.user.UserDefProto.UserDefinition prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code example.UserDefinition}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:example.UserDefinition)
        example.proto.user.UserDefProto.UserDefinitionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return example.proto.user.UserDefProto.internal_static_example_UserDefinition_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return example.proto.user.UserDefProto.internal_static_example_UserDefinition_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                example.proto.user.UserDefProto.UserDefinition.class, example.proto.user.UserDefProto.UserDefinition.Builder.class);
      }

      // Construct using example.proto.user.UserDefProto.UserDefinition.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userName_ = "";

        id_ = 0;

        email_ = "";

        phoneNum_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return example.proto.user.UserDefProto.internal_static_example_UserDefinition_descriptor;
      }

      @java.lang.Override
      public example.proto.user.UserDefProto.UserDefinition getDefaultInstanceForType() {
        return example.proto.user.UserDefProto.UserDefinition.getDefaultInstance();
      }

      @java.lang.Override
      public example.proto.user.UserDefProto.UserDefinition build() {
        example.proto.user.UserDefProto.UserDefinition result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public example.proto.user.UserDefProto.UserDefinition buildPartial() {
        example.proto.user.UserDefProto.UserDefinition result = new example.proto.user.UserDefProto.UserDefinition(this);
        result.userName_ = userName_;
        result.id_ = id_;
        result.email_ = email_;
        result.phoneNum_ = phoneNum_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof example.proto.user.UserDefProto.UserDefinition) {
          return mergeFrom((example.proto.user.UserDefProto.UserDefinition)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(example.proto.user.UserDefProto.UserDefinition other) {
        if (other == example.proto.user.UserDefProto.UserDefinition.getDefaultInstance()) return this;
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (!other.getPhoneNum().isEmpty()) {
          phoneNum_ = other.phoneNum_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        example.proto.user.UserDefProto.UserDefinition parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (example.proto.user.UserDefProto.UserDefinition) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <code>string userName = 1;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userName = 1;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userName = 1;</code>
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>string userName = 1;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 2;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 2;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 3;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object phoneNum_ = "";
      /**
       * <code>string phoneNum = 4;</code>
       */
      public java.lang.String getPhoneNum() {
        java.lang.Object ref = phoneNum_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phoneNum_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string phoneNum = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneNumBytes() {
        java.lang.Object ref = phoneNum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phoneNum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string phoneNum = 4;</code>
       */
      public Builder setPhoneNum(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        phoneNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string phoneNum = 4;</code>
       */
      public Builder clearPhoneNum() {
        
        phoneNum_ = getDefaultInstance().getPhoneNum();
        onChanged();
        return this;
      }
      /**
       * <code>string phoneNum = 4;</code>
       */
      public Builder setPhoneNumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        phoneNum_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:example.UserDefinition)
    }

    // @@protoc_insertion_point(class_scope:example.UserDefinition)
    private static final example.proto.user.UserDefProto.UserDefinition DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new example.proto.user.UserDefProto.UserDefinition();
    }

    public static example.proto.user.UserDefProto.UserDefinition getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserDefinition>
        PARSER = new com.google.protobuf.AbstractParser<UserDefinition>() {
      @java.lang.Override
      public UserDefinition parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserDefinition(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserDefinition> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserDefinition> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public example.proto.user.UserDefProto.UserDefinition getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserDefinitionListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:example.UserDefinitionList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .example.UserDefinition userDefinitions = 1;</code>
     */
    java.util.List<example.proto.user.UserDefProto.UserDefinition> 
        getUserDefinitionsList();
    /**
     * <code>repeated .example.UserDefinition userDefinitions = 1;</code>
     */
    example.proto.user.UserDefProto.UserDefinition getUserDefinitions(int index);
    /**
     * <code>repeated .example.UserDefinition userDefinitions = 1;</code>
     */
    int getUserDefinitionsCount();
    /**
     * <code>repeated .example.UserDefinition userDefinitions = 1;</code>
     */
    java.util.List<? extends example.proto.user.UserDefProto.UserDefinitionOrBuilder> 
        getUserDefinitionsOrBuilderList();
    /**
     * <code>repeated .example.UserDefinition userDefinitions = 1;</code>
     */
    example.proto.user.UserDefProto.UserDefinitionOrBuilder getUserDefinitionsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code example.UserDefinitionList}
   */
  public  static final class UserDefinitionList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:example.UserDefinitionList)
      UserDefinitionListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserDefinitionList.newBuilder() to construct.
    private UserDefinitionList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserDefinitionList() {
      userDefinitions_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserDefinitionList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                userDefinitions_ = new java.util.ArrayList<example.proto.user.UserDefProto.UserDefinition>();
                mutable_bitField0_ |= 0x00000001;
              }
              userDefinitions_.add(
                  input.readMessage(example.proto.user.UserDefProto.UserDefinition.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          userDefinitions_ = java.util.Collections.unmodifiableList(userDefinitions_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return example.proto.user.UserDefProto.internal_static_example_UserDefinitionList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return example.proto.user.UserDefProto.internal_static_example_UserDefinitionList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              example.proto.user.UserDefProto.UserDefinitionList.class, example.proto.user.UserDefProto.UserDefinitionList.Builder.class);
    }

    public static final int USERDEFINITIONS_FIELD_NUMBER = 1;
    private java.util.List<example.proto.user.UserDefProto.UserDefinition> userDefinitions_;
    /**
     * <code>repeated .example.UserDefinition userDefinitions = 1;</code>
     */
    public java.util.List<example.proto.user.UserDefProto.UserDefinition> getUserDefinitionsList() {
      return userDefinitions_;
    }
    /**
     * <code>repeated .example.UserDefinition userDefinitions = 1;</code>
     */
    public java.util.List<? extends example.proto.user.UserDefProto.UserDefinitionOrBuilder> 
        getUserDefinitionsOrBuilderList() {
      return userDefinitions_;
    }
    /**
     * <code>repeated .example.UserDefinition userDefinitions = 1;</code>
     */
    public int getUserDefinitionsCount() {
      return userDefinitions_.size();
    }
    /**
     * <code>repeated .example.UserDefinition userDefinitions = 1;</code>
     */
    public example.proto.user.UserDefProto.UserDefinition getUserDefinitions(int index) {
      return userDefinitions_.get(index);
    }
    /**
     * <code>repeated .example.UserDefinition userDefinitions = 1;</code>
     */
    public example.proto.user.UserDefProto.UserDefinitionOrBuilder getUserDefinitionsOrBuilder(
        int index) {
      return userDefinitions_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < userDefinitions_.size(); i++) {
        output.writeMessage(1, userDefinitions_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < userDefinitions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, userDefinitions_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof example.proto.user.UserDefProto.UserDefinitionList)) {
        return super.equals(obj);
      }
      example.proto.user.UserDefProto.UserDefinitionList other = (example.proto.user.UserDefProto.UserDefinitionList) obj;

      boolean result = true;
      result = result && getUserDefinitionsList()
          .equals(other.getUserDefinitionsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getUserDefinitionsCount() > 0) {
        hash = (37 * hash) + USERDEFINITIONS_FIELD_NUMBER;
        hash = (53 * hash) + getUserDefinitionsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static example.proto.user.UserDefProto.UserDefinitionList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static example.proto.user.UserDefProto.UserDefinitionList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static example.proto.user.UserDefProto.UserDefinitionList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static example.proto.user.UserDefProto.UserDefinitionList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static example.proto.user.UserDefProto.UserDefinitionList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static example.proto.user.UserDefProto.UserDefinitionList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static example.proto.user.UserDefProto.UserDefinitionList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static example.proto.user.UserDefProto.UserDefinitionList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static example.proto.user.UserDefProto.UserDefinitionList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static example.proto.user.UserDefProto.UserDefinitionList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static example.proto.user.UserDefProto.UserDefinitionList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static example.proto.user.UserDefProto.UserDefinitionList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(example.proto.user.UserDefProto.UserDefinitionList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code example.UserDefinitionList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:example.UserDefinitionList)
        example.proto.user.UserDefProto.UserDefinitionListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return example.proto.user.UserDefProto.internal_static_example_UserDefinitionList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return example.proto.user.UserDefProto.internal_static_example_UserDefinitionList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                example.proto.user.UserDefProto.UserDefinitionList.class, example.proto.user.UserDefProto.UserDefinitionList.Builder.class);
      }

      // Construct using example.proto.user.UserDefProto.UserDefinitionList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getUserDefinitionsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (userDefinitionsBuilder_ == null) {
          userDefinitions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          userDefinitionsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return example.proto.user.UserDefProto.internal_static_example_UserDefinitionList_descriptor;
      }

      @java.lang.Override
      public example.proto.user.UserDefProto.UserDefinitionList getDefaultInstanceForType() {
        return example.proto.user.UserDefProto.UserDefinitionList.getDefaultInstance();
      }

      @java.lang.Override
      public example.proto.user.UserDefProto.UserDefinitionList build() {
        example.proto.user.UserDefProto.UserDefinitionList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public example.proto.user.UserDefProto.UserDefinitionList buildPartial() {
        example.proto.user.UserDefProto.UserDefinitionList result = new example.proto.user.UserDefProto.UserDefinitionList(this);
        int from_bitField0_ = bitField0_;
        if (userDefinitionsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            userDefinitions_ = java.util.Collections.unmodifiableList(userDefinitions_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.userDefinitions_ = userDefinitions_;
        } else {
          result.userDefinitions_ = userDefinitionsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof example.proto.user.UserDefProto.UserDefinitionList) {
          return mergeFrom((example.proto.user.UserDefProto.UserDefinitionList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(example.proto.user.UserDefProto.UserDefinitionList other) {
        if (other == example.proto.user.UserDefProto.UserDefinitionList.getDefaultInstance()) return this;
        if (userDefinitionsBuilder_ == null) {
          if (!other.userDefinitions_.isEmpty()) {
            if (userDefinitions_.isEmpty()) {
              userDefinitions_ = other.userDefinitions_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureUserDefinitionsIsMutable();
              userDefinitions_.addAll(other.userDefinitions_);
            }
            onChanged();
          }
        } else {
          if (!other.userDefinitions_.isEmpty()) {
            if (userDefinitionsBuilder_.isEmpty()) {
              userDefinitionsBuilder_.dispose();
              userDefinitionsBuilder_ = null;
              userDefinitions_ = other.userDefinitions_;
              bitField0_ = (bitField0_ & ~0x00000001);
              userDefinitionsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getUserDefinitionsFieldBuilder() : null;
            } else {
              userDefinitionsBuilder_.addAllMessages(other.userDefinitions_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        example.proto.user.UserDefProto.UserDefinitionList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (example.proto.user.UserDefProto.UserDefinitionList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<example.proto.user.UserDefProto.UserDefinition> userDefinitions_ =
        java.util.Collections.emptyList();
      private void ensureUserDefinitionsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          userDefinitions_ = new java.util.ArrayList<example.proto.user.UserDefProto.UserDefinition>(userDefinitions_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          example.proto.user.UserDefProto.UserDefinition, example.proto.user.UserDefProto.UserDefinition.Builder, example.proto.user.UserDefProto.UserDefinitionOrBuilder> userDefinitionsBuilder_;

      /**
       * <code>repeated .example.UserDefinition userDefinitions = 1;</code>
       */
      public java.util.List<example.proto.user.UserDefProto.UserDefinition> getUserDefinitionsList() {
        if (userDefinitionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(userDefinitions_);
        } else {
          return userDefinitionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .example.UserDefinition userDefinitions = 1;</code>
       */
      public int getUserDefinitionsCount() {
        if (userDefinitionsBuilder_ == null) {
          return userDefinitions_.size();
        } else {
          return userDefinitionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .example.UserDefinition userDefinitions = 1;</code>
       */
      public example.proto.user.UserDefProto.UserDefinition getUserDefinitions(int index) {
        if (userDefinitionsBuilder_ == null) {
          return userDefinitions_.get(index);
        } else {
          return userDefinitionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .example.UserDefinition userDefinitions = 1;</code>
       */
      public Builder setUserDefinitions(
          int index, example.proto.user.UserDefProto.UserDefinition value) {
        if (userDefinitionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserDefinitionsIsMutable();
          userDefinitions_.set(index, value);
          onChanged();
        } else {
          userDefinitionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .example.UserDefinition userDefinitions = 1;</code>
       */
      public Builder setUserDefinitions(
          int index, example.proto.user.UserDefProto.UserDefinition.Builder builderForValue) {
        if (userDefinitionsBuilder_ == null) {
          ensureUserDefinitionsIsMutable();
          userDefinitions_.set(index, builderForValue.build());
          onChanged();
        } else {
          userDefinitionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .example.UserDefinition userDefinitions = 1;</code>
       */
      public Builder addUserDefinitions(example.proto.user.UserDefProto.UserDefinition value) {
        if (userDefinitionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserDefinitionsIsMutable();
          userDefinitions_.add(value);
          onChanged();
        } else {
          userDefinitionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .example.UserDefinition userDefinitions = 1;</code>
       */
      public Builder addUserDefinitions(
          int index, example.proto.user.UserDefProto.UserDefinition value) {
        if (userDefinitionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserDefinitionsIsMutable();
          userDefinitions_.add(index, value);
          onChanged();
        } else {
          userDefinitionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .example.UserDefinition userDefinitions = 1;</code>
       */
      public Builder addUserDefinitions(
          example.proto.user.UserDefProto.UserDefinition.Builder builderForValue) {
        if (userDefinitionsBuilder_ == null) {
          ensureUserDefinitionsIsMutable();
          userDefinitions_.add(builderForValue.build());
          onChanged();
        } else {
          userDefinitionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .example.UserDefinition userDefinitions = 1;</code>
       */
      public Builder addUserDefinitions(
          int index, example.proto.user.UserDefProto.UserDefinition.Builder builderForValue) {
        if (userDefinitionsBuilder_ == null) {
          ensureUserDefinitionsIsMutable();
          userDefinitions_.add(index, builderForValue.build());
          onChanged();
        } else {
          userDefinitionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .example.UserDefinition userDefinitions = 1;</code>
       */
      public Builder addAllUserDefinitions(
          java.lang.Iterable<? extends example.proto.user.UserDefProto.UserDefinition> values) {
        if (userDefinitionsBuilder_ == null) {
          ensureUserDefinitionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, userDefinitions_);
          onChanged();
        } else {
          userDefinitionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .example.UserDefinition userDefinitions = 1;</code>
       */
      public Builder clearUserDefinitions() {
        if (userDefinitionsBuilder_ == null) {
          userDefinitions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          userDefinitionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .example.UserDefinition userDefinitions = 1;</code>
       */
      public Builder removeUserDefinitions(int index) {
        if (userDefinitionsBuilder_ == null) {
          ensureUserDefinitionsIsMutable();
          userDefinitions_.remove(index);
          onChanged();
        } else {
          userDefinitionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .example.UserDefinition userDefinitions = 1;</code>
       */
      public example.proto.user.UserDefProto.UserDefinition.Builder getUserDefinitionsBuilder(
          int index) {
        return getUserDefinitionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .example.UserDefinition userDefinitions = 1;</code>
       */
      public example.proto.user.UserDefProto.UserDefinitionOrBuilder getUserDefinitionsOrBuilder(
          int index) {
        if (userDefinitionsBuilder_ == null) {
          return userDefinitions_.get(index);  } else {
          return userDefinitionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .example.UserDefinition userDefinitions = 1;</code>
       */
      public java.util.List<? extends example.proto.user.UserDefProto.UserDefinitionOrBuilder> 
           getUserDefinitionsOrBuilderList() {
        if (userDefinitionsBuilder_ != null) {
          return userDefinitionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(userDefinitions_);
        }
      }
      /**
       * <code>repeated .example.UserDefinition userDefinitions = 1;</code>
       */
      public example.proto.user.UserDefProto.UserDefinition.Builder addUserDefinitionsBuilder() {
        return getUserDefinitionsFieldBuilder().addBuilder(
            example.proto.user.UserDefProto.UserDefinition.getDefaultInstance());
      }
      /**
       * <code>repeated .example.UserDefinition userDefinitions = 1;</code>
       */
      public example.proto.user.UserDefProto.UserDefinition.Builder addUserDefinitionsBuilder(
          int index) {
        return getUserDefinitionsFieldBuilder().addBuilder(
            index, example.proto.user.UserDefProto.UserDefinition.getDefaultInstance());
      }
      /**
       * <code>repeated .example.UserDefinition userDefinitions = 1;</code>
       */
      public java.util.List<example.proto.user.UserDefProto.UserDefinition.Builder> 
           getUserDefinitionsBuilderList() {
        return getUserDefinitionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          example.proto.user.UserDefProto.UserDefinition, example.proto.user.UserDefProto.UserDefinition.Builder, example.proto.user.UserDefProto.UserDefinitionOrBuilder> 
          getUserDefinitionsFieldBuilder() {
        if (userDefinitionsBuilder_ == null) {
          userDefinitionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              example.proto.user.UserDefProto.UserDefinition, example.proto.user.UserDefProto.UserDefinition.Builder, example.proto.user.UserDefProto.UserDefinitionOrBuilder>(
                  userDefinitions_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          userDefinitions_ = null;
        }
        return userDefinitionsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:example.UserDefinitionList)
    }

    // @@protoc_insertion_point(class_scope:example.UserDefinitionList)
    private static final example.proto.user.UserDefProto.UserDefinitionList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new example.proto.user.UserDefProto.UserDefinitionList();
    }

    public static example.proto.user.UserDefProto.UserDefinitionList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserDefinitionList>
        PARSER = new com.google.protobuf.AbstractParser<UserDefinitionList>() {
      @java.lang.Override
      public UserDefinitionList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserDefinitionList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserDefinitionList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserDefinitionList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public example.proto.user.UserDefProto.UserDefinitionList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_UserDefinition_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_example_UserDefinition_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_UserDefinitionList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_example_UserDefinitionList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025user_definition.proto\022\007example\"O\n\016User" +
      "Definition\022\020\n\010userName\030\001 \001(\t\022\n\n\002id\030\002 \001(\005" +
      "\022\r\n\005email\030\003 \001(\t\022\020\n\010phoneNum\030\004 \001(\t\"F\n\022Use" +
      "rDefinitionList\0220\n\017userDefinitions\030\001 \003(\013" +
      "2\027.example.UserDefinitionB\"\n\022example.pro" +
      "to.userB\014UserDefProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_example_UserDefinition_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_example_UserDefinition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_example_UserDefinition_descriptor,
        new java.lang.String[] { "UserName", "Id", "Email", "PhoneNum", });
    internal_static_example_UserDefinitionList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_example_UserDefinitionList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_example_UserDefinitionList_descriptor,
        new java.lang.String[] { "UserDefinitions", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
